@baseUrl=http://localhost:8081


### GET request to example server
GET {{baseUrl}}/api/products/_list

### GET request to example server
GET {{baseUrl}}/api/products/6928660a-0f24-42c6-9347-9ba50c91ba17


### GET request to example server
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "product_id": "6928660a-0f24-42c6-9347-9ba50c91ba17",
  "tradeName": "qq"
}

###
GET http://localhost:4002/api/products/00e2fb1b-d0db-4080-8533-e4931c438800/shopping-lists?limit=Infinity&offset=0&searchText=
    http://localhost:4002/api/products/00e2fb1b-d0db-4080-8533-e4931c438800/items?limit=Infinity&offset=0
x-family-id: d4c47893-ceef-433b-bf8d-83ebb7041600


